/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package io.github.jayhan94

import org.apache.spark.FurySerializer
import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class FurySerializerSuite extends AnyFunSuite {
  test("someLibraryMethod is always true") {
    println("test pass")
  }
}
